import Head from 'next/head'
import { Inter } from '@next/font/google'
import DropK from '/components/DropK.jsx'
import DropAf from '/components/DropAf.jsx'
import DropAh from '/components/DropAh.jsx'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Web3 Dernegi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logoS.jpeg" />
      </Head>
      <div className=" w-full min-w-[200px] min-h-[1200px] h-full ">
            <img
              src='/hatayB.jpeg'
              className=' w-full h-full -z-10 fixed '
            />
        <div className=' text-white font-semibold text-center flex flex-col '>
          <div className=' pt-[1rem] flex flex-col  mx-[5rem] max-sm:mx-[1rem] h-screen '>
            <img
              src='/web3.png'
              className=' max-w-[600px] mx-auto w-full shadow-lg shadow-black'
            
            />
            <div className=' flex text-2xl py-[1rem] '>
            The Southeast region of Turkiye has been hit by the earthquakes with magnitude 7.8 and 7.5, followed by more than 100 aftershocks, which affected more than 20 million people directly. 
            </div>
            <div className=' flex text-sm font-light justify-center pt-1 flex-row flex-wrap'>
              Major earthquakes and aftershocks caused a widespread destruction. The death toll is rising. Millions of people are living in temporary shelters, cars and containers with very limited supplies of food, water, clothes and electricity. To support the lives affected by the earthquake, NGOs started to collect donations. As Web3.0 Technologies Association, we encourage you to spread the news & donate to the official crypto wallet addresses of  &nbsp;  <a href='https://twitter.com/Kizilay/status/1623619343014674432' className=' font-bold text-lg text-red-500 hover:text-red-400'>Kizilay (Red Crescent)</a> &nbsp; &nbsp; <a href='https://www.afad.gov.tr/depremkampanyasi2' className=' font-bold text-lg text-blue-500 hover:text-blue-400'>AFAD (Turkiye Emergency Management Presidency)</a> &nbsp; &nbsp;<a href='https://twitter.com/ahbap/status/1622963311514996739' className=' font-bold text-lg text-green-500 hover:text-green-400'>Ahbap</a>          
            </div>
            <div className=' flex text-sm font-bold font-serif justify-center pt-1  flex-row flex-wrap'> ! Donations will only be made to AHBAP & Kızılay and AFAD  </div>
            <div className=' flex justify-center mt-5 gap-2 flex-row max-sm:flex-col'>
              <DropAf/>
              <DropAh/>
              <DropK/>
            </div>
          </div>
        </div>
n
      </div>

    </>
  )
}
